### ISSUE TITLE
First run of the new Python 3.9 BGCVal on JASMIN - put auxiliary files in a central location

### ISSUE THREAD

**Issue by valeriupredoi** [valeriupredoi/bgc-val#2]
@ledm so I am nearly there - I have created a working conda env for the new BGCVal on JASMIN, and now I am trying to run the basic example you told me to run, unfortunately I am hitting file permissions on JASMIN:
```
(bgcval) [valeriu@sci2 bgc-val]$ ./analysis_timeseries.py u-bc179 debug
analysis-timeseries.py:	Being run at CEDA on  sci2.jasmin.ac.uk
('analysis-timeseries.py:\tBeing run at CEDA on ', 'sci2.jasmin.ac.uk')
('listing model data files:\njobID:\t', 'u-bc179', '\nfile key:\t', 'grid_T', '\ndata folder:\t', '/gws/nopw/j04/ukesm/BGC_data/', '\nannual flag:\t', True)
('listing model data files:', '/gws/nopw/j04/ukesm/BGC_data/u-bc179/u-bc179o_1y_*_grid_T.nc')
('dataset:\tUnable to open', '/home/users/ldemora/workspace/ukesm-validation/data/mesh_mask_eORCA1_wrk.nc')
Traceback (most recent call last):
  File "/home/users/valeriu/bgc-val/bgcvaltools/dataset.py", line 44, in __init__
    self.dataset = netCDF4.Dataset(filename, 'r')
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'/home/users/ldemora/workspace/ukesm-validation/data/mesh_mask_eORCA1_wrk.nc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/users/valeriu/bgc-val/./analysis_timeseries.py", line 4925, in <module>
    main()
  File "/home/users/valeriu/bgc-val/./analysis_timeseries.py", line 4916, in main
    analysis_timeseries(
  File "/home/users/valeriu/bgc-val/./analysis_timeseries.py", line 869, in analysis_timeseries
    masknc = dataset(paths.orcaGridfn, 'r')
  File "/home/users/valeriu/bgc-val/bgcvaltools/dataset.py", line 47, in __init__
    self.dataset = netCDF4.Dataset(
  File "src/netCDF4/_netCDF4.pyx", line 2307, in netCDF4._netCDF4.Dataset.__init__
  File "src/netCDF4/_netCDF4.pyx", line 1925, in netCDF4._netCDF4._ensure_nc_success
PermissionError: [Errno 13] Permission denied: b'/home/users/ldemora/workspace/ukesm-validation/data/mesh_mask_eORCA1_wrk.nc'
(bgcval) [valeriu@sci2 bgc-val]$ ls -la /home/users/ldemora/workspace/ukesm-validation/data/mesh_mask_eORCA1_wrk.nc
ls: cannot access /home/users/ldemora/workspace/ukesm-validation/data/mesh_mask_eORCA1_wrk.nc: Permission denied
````

can we get these files in a central, user-available location please? :beer:

**Comment by valeriupredoi** [comment]
nevermind, I found that mask in `/gws/nopw/j04/esmeval/example_data/bgc/` :grin: And now the whole show is running nicely :partying_face: I'll close this but I'll open another one :+1:
